import type { AdLength, AdPlatform, AdStyle, AdminRole, AppointmentStatus, CarStatus, CrmStatus } from "@/lib/types";

export const adminRu = {
  common: {
    loading: "Загрузка…", save: "Сохранить", saved: "Сохранено", delete: "Удалить", edit: "Редактировать", view: "Просмотреть", duplicate: "Дублировать", cancel: "Отмена", close: "Закрыть", search: "Поиск", filter: "Фильтр", exportCsv: "Экспортировать CSV", upload: "Загрузить", add: "Добавить", copy: "Копировать", copied: "Скопировано", open: "Открыть", create: "Создать", enabled: "Включено", disabled: "Выключено", yes: "Да", no: "Нет", all: "Все", none: "Нет", unassigned: "Не назначен", details: "Подробнее", actions: "Действия", records: "записей", createdAt: "Создано", updatedAt: "Обновлено", status: "Статус", date: "Дата", type: "Тип", language: "Язык", error: "Ошибка", previewNotice: "Демонстрационный режим — изменения не сохраняются в Supabase.",
  },
  auth: { title: "Вход в админ-панель", subtitle: "Защищённый вход через Supabase Auth.", email: "Электронная почта", password: "Пароль", signIn: "Войти", signingIn: "Выполняется вход…", signOut: "Выйти", wrong: "Неверная почта или пароль либо у пользователя нет доступа к админ-панели.", configError: "Добавьте NEXT_PUBLIC_SUPABASE_URL и NEXT_PUBLIC_SUPABASE_ANON_KEY в Cloudflare Pages.", denied: "Доступ запрещён", deniedText: "Пользователь не является активным администратором. Владелец должен назначить ему роль.", noSupabase: "Supabase не настроен", noSupabaseText: "Добавьте публичный URL Supabase и anon key в Cloudflare Pages. Публичный сайт продолжит работать на резервных данных." },
  menu: { dashboard: "Главная", cars: "Автомобили", crm: "CRM", calendar: "Календарь", financing: "Финансирование", adGenerator: "Генератор объявлений", settings: "Настройки", analytics: "Аналитика", team: "Сотрудники" },
  dashboard: { title: "Главная", subtitle: "Продажи, заявки и ближайшие задачи", available: "В наличии", reservedSold: "Зарезервировано / продано", newLeads: "Новые заявки", upcoming: "Ближайшие просмотры", latestLeads: "Последние заявки", popular: "Популярные автомобили", stale: "Давно не обновлялись", staleMore: "Более {days} дней", noLeads: "Заявок пока нет.", noAppointments: "Запланированных просмотров нет.", noAnalytics: "Статистика появится после первых посещений.", allFresh: "Все активные автомобили обновлены." },
  cars: { title: "Автомобили", subtitle: "Перетащите автомобиль, чтобы изменить порядок", add: "Добавить автомобиль", newCar: "Новый автомобиль", core: "Основные данные", photos: "Фотографии", photoHint: "Массовая загрузка, автоматическое сжатие WebP и отдельная миниатюра.", uploadPhotos: "Загрузить фотографии", optimized: "Фотографии сжаты и сохранены в WebP.", optimizing: "Обработка фотографии", deletePhoto: "Удалить фотографию?", mainPhoto: "Сделать главной", deleteConfirm: "Удалить автомобиль {name} и все его фотографии?", copiedSuffix: "копия", copyingPhotos: "Копирование фотографий…", quickPrice: "Новая цена в евро", invalidPrice: "Введите корректную цену.", orderSaved: "Порядок сохранён.", required: "URL и русское или словацкое название обязательны.", saved: "Автомобиль сохранён.", removed: "Автомобиль и фотографии удалены.", contentRoleHint: "Ваша роль позволяет менять описание и фотографии. Цену, статус и финансирование меняют владелец или менеджер.", brand: "Марка", model: "Модель", version: "Версия", slug: "Адрес страницы", year: "Год", mileage: "Пробег (км)", price: "Цена (€)", monthlyPrice: "Платёж в месяц (€)", power: "Мощность (кВт)", engine: "Двигатель", displacement: "Объём двигателя", color: "Цвет", condition: "Состояние", owners: "Количество владельцев", painted: "Окрашенные детали", vin: "VIN (можно скрыть)", fuel: "Топливо", transmission: "Коробка передач", body: "Кузов", drive: "Привод", financing: "Доступно финансирование", calculator: "Показывать калькулятор", featured: "Рекомендуемый", newBadge: "Новинка", goodPrice: "Выгодная цена", titleField: "Название", short: "Краткое описание", description: "Подробное описание", equipment: "Комплектация — один пункт на строку", service: "История обслуживания", damage: "Повреждения", origin: "Происхождение" },
  crm: { title: "CRM заявок", subtitle: "Найдено: {filtered} из {total}", noRecords: "Заявки не найдены", noRecordsText: "Измените фильтры или дождитесь новой заявки.", phone: "Телефон", email: "Электронная почта", car: "Автомобиль", message: "Сообщение", manager: "Ответственный", notes: "Внутренние заметки", save: "Сохранить изменения", saved: "Заявка сохранена.", call: "Позвонить", history: "История статусов", noHistory: "Статус ещё не изменялся.", extra: "Дополнительные данные", from: "С", to: "По", financingType: "Финансирование" },
  calendar: { title: "Календарь", planned: "Запланировано: {count}", list: "Список", calendar: "Календарь", add: "Добавить просмотр", empty: "Календарь пуст", emptyText: "Создайте первый просмотр или тест-драйв.", client: "Клиент", phone: "Телефон", dateTime: "Дата и время", duration: "Продолжительность", car: "Автомобиль", manager: "Ответственный", location: "Место", comment: "Комментарий", save: "Сохранить запись", saved: "Запись сохранена.", complete: "Завершить", cancel: "Отменить запись", noCar: "Без автомобиля" },
  settings: { title: "Настройки сайта", subtitle: "Контакты, социальные сети, баннер, тексты и SEO", business: "Контактные данные", publicHint: "Эти данные отображаются на публичном сайте.", phone: "Телефон", whatsapp: "WhatsApp — только цифры", email: "Электронная почта", address: "Адрес", hours: "Часы работы", timezone: "Часовой пояс", banner: "Ссылка на главный баннер", staleDays: "Считать автомобиль неактуальным через дней", socials: "Социальные сети", saveContacts: "Сохранить контакты", contentSeo: "Тексты и SEO", seoHint: "Для полного обновления статического SEO запустите новую публикацию.", heroTitle: "Главный заголовок", heroLead: "Вводный текст", servicesTitle: "Заголовок услуг", aboutTitle: "Заголовок «О нас»", financingTitle: "Заголовок финансирования", contactsTitle: "Заголовок контактов", seoTitle: "SEO title", seoDescription: "SEO description", contactsSaved: "Контактные данные сохранены.", textsSaved: "Переводы сохранены." },
  analytics: { title: "Аналитика", subtitle: "Просмотры, WhatsApp, заявки и история цен", views: "Просмотры", whatsapp: "Переходы в WhatsApp", leads: "Отправленные заявки", popular: "Популярные автомобили", priceHistory: "История изменения цен", empty: "Данных пока нет", emptyText: "Статистика заполнится после публикации и согласия посетителей на аналитику.", noPrices: "Изменения цен будут записываться автоматически." },
  team: { title: "Сотрудники", subtitle: "Владелец управляет доступом и ролями сотрудников.", add: "Добавить сотрудника", addHint: "Сначала создайте пользователя в Supabase Authentication → Users. Пароль на сайте не создаётся и не хранится.", name: "Имя", role: "Роль", activate: "Активировать", deactivate: "Деактивировать", remove: "Удалить доступ", removeConfirm: "Удалить доступ для {name}?", added: "Сотрудник добавлен.", updated: "Роль сохранена.", removed: "Доступ удалён. Пользователь Supabase Auth сохранён.", empty: "Сотрудников нет" },
  financing: { title: "Финансирование", subtitle: "Условия калькулятора и тексты публичной страницы", calculator: "Калькулятор", ranges: "Ограничения и значения по умолчанию", minAmount: "Минимальная сумма финансирования (€)", maxAmount: "Максимальная сумма финансирования (€)", minTerm: "Минимальный срок (месяцев)", maxTerm: "Максимальный срок (месяцев)", terms: "Доступные сроки через запятую", rate: "Ставка по умолчанию (% в год)", minDownEur: "Минимальный взнос (€)", minDownPercent: "Минимальный взнос (%)", fixedFee: "Фиксированная комиссия (€)", percentFee: "Процентная комиссия (%)", localized: "Тексты страницы", titleField: "Заголовок страницы", description: "Описание страницы", warning: "Предупреждение", documents: "Документы — один пункт на строку", steps: "Этапы — один пункт на строку", faq: "FAQ — вопрос и ответ через символ |", applyButton: "Текст кнопки заявки", save: "Сохранить настройки", saved: "Настройки финансирования сохранены." },
  ads: { title: "Генератор объявлений", subtitle: "Шаблонная генерация без платного AI API", selectCar: "Выберите автомобиль", platform: "Площадка", length: "Длина", style: "Стиль", generate: "Создать объявление", regenerate: "Создать заново", copyTitle: "Скопировать заголовок", copyText: "Скопировать текст", copyAll: "Скопировать всё", save: "Сохранить вариант", openCar: "Открыть автомобиль", heading: "Заголовок", body: "Текст объявления", hashtags: "Хештеги", history: "Сохранённые варианты", noHistory: "Сохранённых объявлений пока нет.", saved: "Объявление сохранено.", deleted: "Объявление удалено.", deleteConfirm: "Удалить сохранённое объявление?", basedOn: "Создать вариант на основе", chooseCar: "Сначала выберите автомобиль." },
} as const;

export const adminRoleLabels: Record<AdminRole, string> = { owner: "Владелец", manager: "Менеджер", content_manager: "Контент-менеджер", viewer: "Наблюдатель" };
export const adminCarStatusLabels: Record<CarStatus, string> = { draft: "Черновик", available: "В наличии", reserved: "Зарезервирован", sold: "Продан", hidden: "Скрыт" };
export const adminCrmStatusLabels: Record<CrmStatus, string> = { new: "Новая", contacted: "Связались", appointment: "Назначен просмотр", thinking: "Думает", financing: "Финансирование", reserved: "Зарезервирован", documents_requested: "Документы запрошены", documents_received: "Документы получены", submitted: "Отправлено на рассмотрение", decision_pending: "Ожидается решение", approved: "Одобрено", rejected: "Отказано", contract_signed: "Договор подписан", completed: "Завершено" };
export const adminAppointmentStatusLabels: Record<AppointmentStatus, string> = { scheduled: "Запланировано", completed: "Завершено", cancelled: "Отменено" };
export const adPlatformLabels: Record<AdPlatform, string> = { bazos: "Bazoš", facebook: "Facebook Marketplace", instagram: "Instagram", tiktok: "TikTok", whatsapp: "WhatsApp", telegram: "Telegram", universal: "Универсальное объявление" };
export const adLengthLabels: Record<AdLength, string> = { short: "Короткое", standard: "Стандартное", detailed: "Подробное" };
export const adStyleLabels: Record<AdStyle, string> = { business: "Деловой", friendly: "Дружелюбный", sales: "Продающий", neutral: "Нейтральный", premium: "Премиальный" };

const otherOptions: Record<string, string> = { all: "Все", lead: "Обычная заявка", contact: "Контакт", service: "Услуга", test_drive: "Тест-драйв", financing: "Финансирование", diesel: "Дизель", petrol: "Бензин", hybrid: "Гибрид", electric: "Электромобиль", automatic: "Автомат", manual: "Механика", sedan: "Седан", wagon: "Универсал", suv: "Кроссовер / SUV", hatchback: "Хэтчбек", fwd: "Передний", rwd: "Задний", awd: "Полный" };

export function adminOptionLabel(value: string) {
  return (adminCarStatusLabels as Record<string, string>)[value] || (adminCrmStatusLabels as Record<string, string>)[value] || (adminAppointmentStatusLabels as Record<string, string>)[value] || (adminRoleLabels as Record<string, string>)[value] || (adPlatformLabels as Record<string, string>)[value] || (adLengthLabels as Record<string, string>)[value] || (adStyleLabels as Record<string, string>)[value] || otherOptions[value] || value;
}

export function replaceTemplate(template: string, values: Record<string, string | number>) { return Object.entries(values).reduce((text, [key, value]) => text.replaceAll(`{${key}}`, String(value)), template); }

export function adminErrorMessage(error?: { message?: string } | string | null) {
  const value = typeof error === "string" ? error : error?.message || "";
  const normalized = value.toLowerCase();
  if (normalized.includes("duplicate") || normalized.includes("unique")) return "Ошибка: такая запись уже существует.";
  if (normalized.includes("permission") || normalized.includes("policy") || normalized.includes("row-level") || normalized.includes("rls")) return "Ошибка: у вашей роли нет прав для этой операции.";
  if (normalized.includes("jwt") || normalized.includes("session") || normalized.includes("auth")) return "Ошибка: сеанс истёк. Войдите в админ-панель повторно.";
  if (normalized.includes("network") || normalized.includes("fetch") || normalized.includes("timeout")) return "Ошибка соединения с базой данных. Повторите попытку.";
  return "Ошибка: операция не выполнена. Проверьте данные и повторите попытку.";
}
