import { AlertTriangle, Aperture, ArrowRight, Camera, Check, Clock3, Mail, MapPin, Phone, Send, Share2, ShieldCheck, Video } from "lucide-react";
import Link from "next/link";
import { CatalogClient } from "@/components/catalog-client";
import { ContactForm } from "@/components/forms/contact-form";
import { FinancingForm } from "@/components/forms/financing-form";
import { SectionHeading } from "@/components/section-heading";
import { financingInfo, inspectionInfo, servicePackages } from "@/data/business-info";
import { demoCars } from "@/data/cars";
import { getDictionary, localizedPath } from "@/lib/i18n";
import type { Locale } from "@/lib/types";

export function PageHero({ eyebrow, title, lead }: { eyebrow: string; title: string; lead: string }) { return <section className="neon-grid relative overflow-hidden border-b border-acid/20 bg-black py-20 text-white sm:py-28"><div className="absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(circle_at_center,rgba(223,39,127,.2),transparent_65%)]"/><div className="shell relative"><div className="eyebrow text-white/50">{eyebrow}</div><h1 className="page-title max-w-5xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-relaxed text-white/55">{lead}</p></div></section>; }

export function CatalogPage({ locale }: { locale: Locale }) { const d = getDictionary(locale); return <><PageHero eyebrow={d.catalog.eyebrow} title={d.catalog.title} lead={d.catalog.lead}/><section className="section-pad"><div className="shell"><CatalogClient cars={demoCars} locale={locale}/></div></section></>; }

export function ServicesPage({ locale }: { locale: Locale }) {
  const d = getDictionary(locale);
  const services = servicePackages[locale];
  const inspection = inspectionInfo[locale];
  return <><PageHero {...d.servicesPage}/><section className="section-pad"><div className="shell"><div className="grid gap-4 lg:grid-cols-3">{services.map((service, index) => <article key={service.title} className="card flex flex-col p-6"><div className="flex items-start justify-between gap-4"><span className="text-sm font-black text-acid">0{index + 1}</span><span className="rounded-lg border border-acid/35 bg-acid/10 px-3 py-1.5 text-xl font-black text-acid">{service.price}</span></div><h2 className="mt-8 text-2xl font-black tracking-tight">{service.title}</h2><p className="mt-3 flex-1 text-white/55">{service.note}</p><Link href={`${localizedPath(locale, "contacts")}?service=${index + 1}`} className="mt-7 flex items-center gap-2 font-black text-acid">{d.servicesPage.request}<ArrowRight size={17}/></Link></article>)}</div><div className="mt-12 grid gap-5 lg:grid-cols-2"><article className="neon-panel rounded-[24px] p-7"><ShieldCheck className="text-acid"/><h2 className="mt-6 text-2xl font-black">{inspection.title}</h2><ul className="mt-6 grid gap-3">{inspection.items.map((item) => <li key={item} className="flex gap-3 text-white/65"><Check className="shrink-0 text-acid" size={19}/>{item}</li>)}</ul></article><article className="neon-panel rounded-[24px] p-7"><AlertTriangle className="text-acid"/><h2 className="mt-6 text-2xl font-black">{inspection.warrantyTitle}</h2><p className="mt-5 text-white/60">{inspection.warranty}</p></article></div><div className="mt-16"><SectionHeading eyebrow="GTA_Bratislava" title={d.sections.services}/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{d.services.map((service, index) => <Link key={service} href={`${localizedPath(locale, "contacts")}?service=${index + 1}`} className="dark-card group flex min-h-28 items-center justify-between gap-4 p-5 font-black hover:border-acid"><span>{service}</span><ArrowRight className="shrink-0 text-acid transition-transform group-hover:translate-x-1" size={19}/></Link>)}</div></div></div></section></>;
}

export function FinancingPage({ locale }: { locale: Locale }) {
  const d = getDictionary(locale);
  const info = financingInfo[locale];
  return <><PageHero eyebrow={d.financingPage.eyebrow} title={d.financingPage.title} lead={d.financingPage.lead}/><section className="section-pad"><div className="shell"><div className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><article className="neon-panel rounded-[24px] p-6 sm:p-8"><ShieldCheck className="text-acid"/><h2 className="mt-6 text-2xl font-black">{info.documentsTitle}</h2><ul className="mt-6 grid gap-3">{info.documents.map((item) => <li key={item} className="flex gap-3 text-white/65"><Check className="mt-0.5 shrink-0 text-acid" size={18}/>{item}</li>)}</ul></article><div className="grid gap-5"><article className="neon-panel rounded-[24px] p-6 sm:p-8"><h2 className="text-2xl font-black">{info.termsTitle}</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{info.terms.map((term) => <div key={term.label} className="rounded-xl border border-white/10 bg-white/[.035] p-4"><p className="text-xs font-bold uppercase tracking-wider text-white/40">{term.label}</p><p className="mt-2 font-black text-acid">{term.value}</p></div>)}</div></article><article className="rounded-[20px] border border-acid/35 bg-acid/10 p-6"><h2 className="flex items-center gap-3 text-xl font-black"><AlertTriangle className="text-acid"/>{info.importantTitle}</h2><ul className="mt-4 grid gap-2 text-sm text-white/65">{info.important.map((item) => <li key={item}>• {item}</li>)}</ul></article></div></div><div className="mt-12 grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="section-title">{info.supportTitle}</h2><div className="mt-7 grid gap-3">{info.support.map((item, index) => <div key={item} className="flex items-center gap-3 border-t border-acid/20 pt-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-acid text-sm font-black text-black">{index + 1}</span><span className="font-bold">{item}</span></div>)}</div><p className="mt-8 text-sm leading-relaxed text-white/45">{d.financingPage.warning}</p></div><FinancingForm locale={locale}/></div></div></section></>;
}

export function AboutPage({ locale }: { locale: Locale }) { const d = getDictionary(locale); return <><PageHero eyebrow={d.about.eyebrow} title={d.about.title} lead={d.about.lead}/><section className="section-pad"><div className="shell"><div className="grid gap-5 md:grid-cols-2"><PhotoPlaceholder label={d.about.team}/><PhotoPlaceholder label={d.about.place}/></div><div className="mt-16 grid gap-10 lg:grid-cols-2"><div><div className="eyebrow text-white/50">GTA_Bratislava</div><h2 className="section-title">{d.about.approach}</h2></div><div><p className="text-xl leading-relaxed text-white/60">{d.about.approachText}</p><div className="mt-8 grid gap-3">{d.benefits.map((item) => <div key={item.title} className="flex gap-3 border-t border-acid/20 pt-4"><Check className="shrink-0 text-acid"/><div><h3 className="font-black">{item.title}</h3><p className="mt-1 text-sm text-white/50">{item.text}</p></div></div>)}</div></div></div></div></section></>; }
function PhotoPlaceholder({ label }: { label: string }) { return <div className="neon-panel grid aspect-[4/3] place-items-center rounded-[24px]"><div className="text-center text-white/45"><Camera className="mx-auto text-acid" size={34}/><p className="mt-3 font-bold">{label}</p></div></div>; }

export function ContactsPage({ locale }: { locale: Locale }) { const d = getDictionary(locale); const socials = [["Instagram",d.instagram,Aperture],["TikTok",d.tiktok,Video],["Facebook",d.facebook,Share2],["Telegram",d.telegram,Send]] as const; return <><PageHero eyebrow={d.contacts.eyebrow} title={d.contacts.title} lead={d.contacts.lead}/><section className="section-pad"><div className="shell grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3"><ContactItem icon={Phone} label={d.contacts.phone} value={d.phone} href={`tel:${d.phone.replace(/\s/g,"")}`}/><ContactItem icon={Mail} label={d.contacts.email} value={d.email} href={`mailto:${d.email}`}/><ContactItem icon={MapPin} label={d.contacts.address} value={d.address}/><ContactItem icon={Clock3} label={d.contacts.hours} value={d.contacts.hoursValue}/><div className="flex gap-2 pt-3">{socials.map(([name, href, Icon]) => <a key={name} href={href} target="_blank" rel="noreferrer" aria-label={name} className="grid h-12 w-12 place-items-center rounded-xl border border-acid/35 bg-black text-acid hover:bg-acid hover:text-black"><Icon size={19}/></a>)}</div></div><div className="card p-6 sm:p-8"><ContactForm locale={locale}/></div></div><div className="neon-panel mt-8 grid min-h-[360px] place-items-center rounded-[24px]"><div className="text-center"><MapPin className="mx-auto text-acid"/><h2 className="mt-5 text-2xl font-black">{d.contacts.map}</h2><p className="mt-2 text-white/50">{d.contacts.mapNote}</p><p className="mt-5 font-black text-acid">{d.phone}</p></div></div></section></>; }
function ContactItem({ icon: Icon, label, value, href }: { icon: typeof Phone; label: string; value: string; href?: string }) { const content = <><Icon className="text-acid"/><div><p className="text-xs font-black uppercase tracking-wider text-white/40">{label}</p><p className="mt-1 font-black">{value}</p></div></>; return href ? <a href={href} className="card flex items-center gap-4 p-5 hover:border-acid">{content}</a> : <div className="card flex items-center gap-4 p-5">{content}</div>; }

export function LegalPage({ locale, kind }: { locale: Locale; kind: "privacy" | "cookies" | "data" | "terms" }) { const d = getDictionary(locale); const title = d.legal[kind]; const paragraphs = legalText(locale, kind); return <><PageHero eyebrow={d.footer.legal} title={title} lead={d.legal.updated}/><article className="section-pad"><div className="shell max-w-3xl"><div className="grid gap-8">{paragraphs.map((block) => <section key={block.title}><h2 className="text-2xl font-black">{block.title}</h2><p className="mt-3 whitespace-pre-line leading-7 text-white/60">{block.text}</p></section>)}</div></div></article></>; }
function legalText(locale: Locale, kind: string) { const base = {
  sk: { controller: "Prevádzkovateľ a kontakt", controllerText: "Prevádzkovateľom stránky je GTA_Bratislava. Kontaktné údaje pred spustením doplňte o obchodné meno, IČO a úplnú adresu. Otázky posielajte na e-mail uvedený na stránke Kontakt.", purpose: "Účel a rozsah", purposeText: "Spracúvame iba údaje, ktoré zadáte do kontaktného formulára alebo žiadosti o financovanie, aby sme mohli odpovedať a vybaviť vašu požiadavku. Citlivé dokumenty cez bežný formulár neposielajte.", rights: "Vaše práva", rightsText: "Môžete požiadať o prístup, opravu, vymazanie, obmedzenie spracúvania alebo namietať. Súhlas môžete kedykoľvek odvolať.", security: "Bezpečnosť a uchovávanie", securityText: "Údaje chránime primeranými technickými a organizačnými opatreniami a uchovávame len počas času potrebného na vybavenie požiadavky a splnenie zákonných povinností." },
  ua: { controller: "Оператор і контакти", controllerText: "Оператор сайту — GTA_Bratislava. Перед запуском додайте юридичну назву, реєстраційний номер і повну адресу. Питання надсилайте на e-mail зі сторінки Контакти.", purpose: "Мета й обсяг", purposeText: "Ми обробляємо лише дані, які ви вводите у форму контакту або заявку на фінансування, щоб відповісти та опрацювати запит. Не надсилайте чутливі документи через звичайну форму.", rights: "Ваші права", rightsText: "Ви можете попросити доступ, виправлення, видалення, обмеження обробки або заперечити проти неї. Згоду можна відкликати будь-коли.", security: "Безпека та зберігання", securityText: "Ми застосовуємо належні технічні й організаційні заходи та зберігаємо дані лише стільки, скільки потрібно для запиту й законних обов’язків." },
  ru: { controller: "Оператор и контакты", controllerText: "Оператор сайта — GTA_Bratislava. Перед запуском добавьте юридическое название, регистрационный номер и полный адрес. Вопросы направляйте на e-mail со страницы Контакты.", purpose: "Цель и объём", purposeText: "Мы обрабатываем только данные, которые вы вводите в контактную форму или заявку на финансирование, чтобы ответить и обработать запрос. Не отправляйте чувствительные документы через обычную форму.", rights: "Ваши права", rightsText: "Вы можете запросить доступ, исправление, удаление, ограничение обработки или возразить против неё. Согласие можно отозвать в любое время.", security: "Безопасность и хранение", securityText: "Мы применяем разумные технические и организационные меры и храним данные только столько, сколько нужно для запроса и выполнения законных обязанностей." },
  en: { controller: "Operator and contact", controllerText: "The website operator is GTA_Bratislava. Before launch, add the legal business name, registration number and complete address. Send questions to the email address shown on the Contacts page.", purpose: "Purpose and scope", purposeText: "We process only the information you enter in the contact or financing forms so that we can respond to and handle your request. Do not send sensitive documents through a standard website form.", rights: "Your rights", rightsText: "You may request access, correction, deletion or restriction of processing, or object to processing. Consent may be withdrawn at any time.", security: "Security and retention", securityText: "We apply appropriate technical and organisational measures and retain information only for as long as necessary to handle the request and meet legal obligations." },
  }[locale];
  if (kind === "cookies") return [{title: base.purpose, text: locale === "sk" ? "Nevyhnutné cookies zabezpečujú jazyk, bezpečnosť administrácie a voľbu cookies. Analytické alebo marketingové cookies sa nesmú načítať pred súhlasom." : locale === "ua" ? "Необхідні cookies забезпечують мову, безпеку адміністрування та вибір cookies. Аналітичні або маркетингові cookies не завантажуються до згоди." : locale === "ru" ? "Необходимые cookies обеспечивают язык, безопасность администрирования и выбор cookies. Аналитические или маркетинговые cookies не загружаются до согласия." : "Essential cookies provide language selection, administration security and cookie preferences. Analytics or marketing cookies are not loaded before consent."},{title: base.rights,text: base.rightsText}];
  if (kind === "terms") return [{title: base.controller,text: base.controllerText},{title: base.purpose,text: locale === "sk" ? "Obsah stránky je informatívny. Cena, dostupnosť a stav vozidla sa potvrdzujú pred podpisom zmluvy. Financovanie podlieha rozhodnutiu partnera." : locale === "ua" ? "Інформація на сайті має довідковий характер. Ціну, наявність і стан авто підтверджують до підписання договору. Фінансування залежить від рішення партнера." : locale === "ru" ? "Информация на сайте носит справочный характер. Цена, наличие и состояние авто подтверждаются до подписания договора. Финансирование зависит от решения партнёра." : "Website content is provided for information only. Vehicle price, availability and condition are confirmed before a contract is signed. Financing is subject to the partner’s decision."},{title: base.security,text: base.securityText}];
  return [{title: base.controller,text: base.controllerText},{title: base.purpose,text: base.purposeText},{title: base.rights,text: base.rightsText},{title: base.security,text: base.securityText}]; }
